### ISSUE TITLE
Dataset balancing for OULU-NPU

### ISSUE THREAD

**Issue by alvarobasi** [ZitongYu/CDCN#55]
Hey! I'm trying to reproduce your results on OULU-NPU Protocol 1 with CDCN. Have you performed dataset balancing by downsampling the majority class? Or the training has been done as is in the Protocol 1 txt? Thanks!

**Comment by showbit01** [comment]
> OULU-NPU

Hey are you working on face antispoofing?

**Comment by alvarobasi** [comment]
@showbit01 Yes!

**Comment by showbit01** [comment]
Cool,
I am also working with oulu dataset with cdcn or more generalized domain approach for unseen scenerios.
if anything is there we can discuss the work

**Comment by alvarobasi** [comment]
That sounds interesting. For the moment with this model I have two main questions, one related to this thread. Is it necessary to perform dataset balancing, as we are not using any sort of binary cross entropy here? And second, how to treat an inference output, shall we average the result to get the prediction? @showbit01

**Comment by showbit01** [comment]
> That sounds interesting. For the moment with this model I have two main questions, one related to this thread. Is it necessary to perform dataset balancing, as we are not using any sort of binary cross entropy here? And second, how to treat an inference output, shall we average the result to get the prediction? @showbit01 



1.Data balancing is just for accuracy like in this case whether it's fake or real,the majority class if for fake samples then its true negative will be higher but true positive is lower..But that's okay to go with it if any pattern you want to see.


2.for inference you can take the average by just np.mean()
Or otherwise  overlaid the output to small grid of cells like n*n and take the mean of each and generate n*n final vector fed it to the svm with radial basis kernal..you can play with value of n and svms..
For number of svms use gaussian mixture model to fit the distribution of input image sizes..

**Comment by showbit01** [comment]
Sorry for delay ,rarely used GitHub for now we can chat on mail: shobhits69@gmail.com
